export const STOPWORDS_PT = new Set([
  'de', 'da', 'do', 'em', 'para', 'com', 'por', 'uma', 'como', 'mais', 'das', 'dos',
  'a', 'e', 'o', 'que', 'é', 'são', 'seu', 'sua', 'seus', 'suas', 'um', 'na', 'no',
  'nas', 'nos', 'ao', 'aos', 'à', 'às', 'pelo', 'pela', 'pelos', 'pelas', 'num', 'numa',
  'dum', 'duma', 'este', 'esta', 'estes', 'estas', 'isto', 'esse', 'essa', 'esses', 'essas',
  'isso', 'aquele', 'aquela', 'aqueles', 'aquelas', 'aquilo', 'qual', 'quais', 'cujo', 'cuja',
  'cujos', 'cujas', 'quanto', 'quanta', 'quantos', 'quantas', 'tanto', 'tanta', 'tantos', 'tantas',
  'onde', 'quando', 'como', 'porque', 'pois', 'portanto', 'entretanto', 'contudo', 'todavia',
  'então', 'assim', 'já', 'ainda', 'apenas', 'só', 'somente', 'também', 'tampouco',
  'ou', 'e', 'nem', 'mas', 'porém', 'contudo', 'todavia', 'entretanto', 'logo', 'portanto',
  'pois', 'que', 'se', 'embora', 'conquanto', 'como', 'quando', 'enquanto', 'à medida que',
  'à proporção que', 'quanto mais', 'quanto menos', 'por mais que', 'por menos que',
  'bem como', 'assim como', 'do mesmo modo', 'outrossim', 'ademais', 'além disso',
  'todos', 'todas', 'os', 'as', 'lhe', 'lhes', 'me', 'te', 'se', 'nos', 'vos',
  'o', 'a', 'os', 'as', 'lo', 'la', 'los', 'las', 'no', 'na', 'nos', 'nas',
  'eu', 'tu', 'ele', 'ela', 'nós', 'vós', 'eles', 'elas', 'meu', 'teu', 'seu',
  'minha', 'tua', 'sua', 'nossos', 'nossas', 'vossos', 'vossas', 'dela', 'dele',
  'deles', 'delas', 'nisto', 'nisso', 'naquilo', 'àquele', 'àquela', 'àqueles', 'àquelas',
  'foi', 'foram', 'ser', 'sendo', 'sido', 'ter', 'tendo', 'tido', 'tem', 'têm',
  'havia', 'houve', 'houver', 'haver', 'havendo', 'havido', 'há', 'hão',
  'vai', 'vão', 'ir', 'indo', 'ido', 'vamos', 'ides', 'iam',
  'pode', 'podem', 'poder', 'podendo', 'podido', 'pôde', 'puder',
  'deve', 'devem', 'dever', 'devendo', 'devido', 'quis', 'quiser',
  'fez', 'fazem', 'fazer', 'fazendo', 'feito',
  'disse', 'dizem', 'dizer', 'dizendo', 'dito',
  'houveram', 'houverão', 'houvera', 'houverem',
  'etc', 'ex', 'exemplo', 'fig', 'figura', 'tabela',
  'ano', 'anos', 'dia', 'dias', 'mês', 'meses', 'pra',
  'pro', 'vou', 'tá', 'tô', 'né', 'sim', 'não', 'obrigado',
  'sr', 'sra', 'dr', 'dra', 'eng', 'profa',
  'art', '$', 'r$', 'nº', '°',
]);
